In [2]:
# import Pandas
import pandas as pd

# import os
import os

# import numpy
import numpy as np

# import pyplot
import matplotlib.pyplot as plt

### import csv file

In [3]:
physical_chara = pd.read_csv(os.path.join("all_seasons.csv"))
physical_chara.head()

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Chris Robinson,VAN,23.0,195.58,90.71840,Western Kentucky,USA,1996,2,...,4.6,1.7,1.6,-11.4,0.039,0.088,0.155,0.486,0.156,1996-97
1,1,Matt Fish,MIA,27.0,210.82,106.59412,North Carolina-Wilmington,USA,1992,2,...,0.3,0.8,0.0,-15.1,0.143,0.267,0.265,0.333,0.000,1996-97
2,2,Matt Bullard,HOU,30.0,208.28,106.59412,Iowa,USA,Undrafted,Undrafted,...,4.5,1.6,0.9,0.9,0.016,0.115,0.151,0.535,0.099,1996-97
3,3,Marty Conlon,BOS,29.0,210.82,111.13004,Providence,USA,Undrafted,Undrafted,...,7.8,4.4,1.4,-9.0,0.083,0.152,0.167,0.542,0.101,1996-97
4,4,Martin Muursepp,DAL,22.0,205.74,106.59412,None,USA,1996,1,...,3.7,1.6,0.5,-14.5,0.109,0.118,0.233,0.482,0.114,1996-97

### Restructuring the dataframe and change the season column format

In [14]:
# change the order of columns and remove the same columns in stats data
phy_df = physical_chara[["season", "player_name","age","player_height","player_weight","draft_year","gp","reb","net_rating","oreb_pct","dreb_pct","usg_pct","ts_pct","ast_pct"]]
# rename columns
phy_df = phy_df.rename(columns={"player_name": "Name","age":"Age","season":"Season"})

# extract first 4 characters from Season column and set it as Year column
phy_df['Year'] = [x[:4] for x in phy_df['Season']]
# set the Year value as interger
phy_df.Year = phy_df.Year.astype(int)

phy_df.dtypes

Season            object
Name              object
Age              float64
player_height    float64
player_weight    float64
draft_year        object
gp                 int64
reb              float64
net_rating       float64
oreb_pct         float64
dreb_pct         float64
usg_pct          float64
ts_pct           float64
ast_pct          float64
Year               int64
dtype: object

In [16]:
phy_df.head()

,Season,Name,Age,player_height,player_weight,draft_year,gp,reb,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,Year
0,1996-97,Chris Robinson,23.0,195.58,90.71840,1996,41,1.7,-11.4,0.039,0.088,0.155,0.486,0.156,1996
1,1996-97,Matt Fish,27.0,210.82,106.59412,1992,6,0.8,-15.1,0.143,0.267,0.265,0.333,0.000,1996
2,1996-97,Matt Bullard,30.0,208.28,106.59412,Undrafted,71,1.6,0.9,0.016,0.115,0.151,0.535,0.099,1996
3,1996-97,Marty Conlon,29.0,210.82,111.13004,Undrafted,74,4.4,-9.0,0.083,0.152,0.167,0.542,0.101,1996
4,1996-97,Martin Muursepp,22.0,205.74,106.59412,1996,42,1.6,-14.5,0.109,0.118,0.233,0.482,0.114,1996